### ISSUE TITLE
Page showing old team data:

### ISSUE THREAD

**Issue by Shubhambawner** [ECellNitrr/EcellWeb2k22#13]
PR team in CA-Portal shows old data of the team members
@lawanyabaghel

**Comment by lawanyabaghel** [comment]
Resolved

**Comment by sahil9001** [comment]
> PR team in CA-Portal shows old data of the team members @lawanyabaghel

You can assign @lawanyabaghel from the right hand sidebar under the `Assignees` tag. That's a better practice
