### ISSUE TITLE
Minor Updates

### ISSUE THREAD

**Issue by AyushAgrawal25** [ECellNitrr/EcellWeb2k22#21]
- Update the events page with the current year data i.e. 2022's data.
- Update the Footer with the new OC contacts
- Update the tagline in the Footer (Make the tagline a constant variable in the constants.js file)
- Update the mentor's page, it is currently fetching data till 2020. Update it to 2022.
- Update the Navbar by removing CA Portal and Startup portal routes.
- Update the sponsor's link to show data for 2022 as default.

**Comment by Shubhambawner** [comment]
for last point, 
sponsors data is available only till 2019 from backend ( API spons_years/ )

**Comment by sahil9001** [comment]
> for last point, sponsors data is available only till 2019 from backend ( API spons_years/ )

Yeah, some data has not been given by the team. So waiting for it currently.
